### ISSUE TITLE
Multithreaded spinner in gazebo_visibility_ros?

### ISSUE THREAD

**Issue by fairlight1337** [cram2/cram_gazebo#5]
When running Gazebo with the plugin, I get

``` bash
[ INFO] [1468402692.831128898]: Starting up the QueryGazeboVisibility service.
[ERROR] [1468402692.832316738]: SingleThreadedSpinner: You've attempted to call spin from multiple threads.  Use a MultiThreadedSpinner instead.
```

@mpomarlan is this intended?

**Comment by mpomarlan** [comment]
Ok, NOW I've merged the pull request where this is fixed :p 

You shouldn't see the warning now. It appears a ros::spin is redundant when Load-ing a gazebo plugin.
